site_name: "mango4j-crypto"
site_description: Framework to help developers implement application level encryption, powered by Mango
site_url: https://bitstep-ie.github.io/mango4j-crypto/
repo_url: https://github.com/bitstep-ie/mango4j-crypto
repo_name: bitstep-ie/mango4j-crypto
docs_dir: ./docs


theme:
  name: material
  logo: assets/mango-black.png
  features:
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      code: github           # light mode code block style
    - scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      code: monokai

extra:
  favicon: assets/favicon.ico
  version:
    provider: mike

nav:
  - Guide: guide/guide.md
  - Delegates:
      - Test Delegates: delegates/test-delegates.md
      - Core Delegates: delegates/core-delegates.md
      - AWS Delegate: delegates/aws-delegate.md
  - General Documentation:
      - Encryption:
        - Delegates: delegates/test-delegates.md 
        - Rotation: delegates/aws-delegates.md


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: false
      linenums: true
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
