name: Release

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'yes' to confirm execution"
        required: true
        default: "no"

permissions:
  contents: write

jobs:
  run:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}


      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install docs dependencies
        working-directory: documentation
        run: pip install -r requirements.txt

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages
        run: git fetch origin gh-pages:gh-pages || echo "No gh-pages branch yet"

      - name: Release Version Deploy
        working-directory: documentation
#        if: ${{ github.event.release && github.event.release.tag_name != '' }}
        run: |
          MANGO4J_CRYPTO_LATEST_VERSION=0.1.0 \
          mike deploy 0.1.0 latest -u --push
# mike deploy ${{ github.event.release.tag_name }} latest -u --push

      - name: Default latest
        working-directory: documentation
        run: mike set-default latest --allow-undefined --push
